service:
  name: quik-provider
  active-sessions-container:
    enabled: true
  standard-settings-controller:
    enabled: true
  simple-worker:
    enabled: true
    name: simple-worker
    wait-on-stop-ms: 1000
    wait-on-restart-ms: 20000
    min-time-per-iteration-ms: 1000
    timeout-runner-life-ms: 60000
    print-statistics-every-ms: 1000
  redis:
    server: localhost
    port: 6379
    outcome-collections:
      simple-configuration.enabled: true
      standard-uploader.enabled: true
  channels-api:
    dris-snapshots:
      places-v1.enabled: true
      provider-types-v1.enabled: true
      providers-v1.enabled: true
      instrument-types-v1.enabled: true

# Логирование
logging:
  level:
    org.springframework: info
    org.springframework.orm: info
    org.springframework.web: info

# Настройки Сервера
server:
  port: 7001

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate # create, create-drop, update, validate
      naming.physical-strategy: ru.gx.core.data.naming.PhysicalNamingStrategyQuotedImpl
  datasource:
    url: jdbc:postgresql://localhost:5432/gxfin_dris
    username: gxfin
    password: 12033021
    hikari:
      maximum-pool-size: 2

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true